name: Build & Release Debug APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      STAGING_OAUTH_CLIENT_ID: ${{ secrets.STAGING_OAUTH_CLIENT_ID }}
      STAGING_OAUTH_CLIENT_SECRET: ${{ secrets.STAGING_OAUTH_CLIENT_SECRET }}
      PRODUCTION_OAUTH_CLIENT_ID: ${{ secrets.PRODUCTION_OAUTH_CLIENT_ID }}
      PRODUCTION_OAUTH_CLIENT_SECRET: ${{ secrets.PRODUCTION_OAUTH_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: touch local.properties
      - run: echo "staging.oauth.client.id=\"$STAGING_OAUTH_CLIENT_ID\"" > local.properties
      - run: echo "staging.oauth.client.secret=\"$STAGING_OAUTH_CLIENT_SECRET\"" >> local.properties
      - run: echo "production.oauth.client.id=\"$PRODUCTION_OAUTH_CLIENT_ID\"" >> local.properties
      - run: echo "production.oauth.client.secret=\"$PRODUCTION_OAUTH_CLIENT_SECRET\"" >> local.properties
      - name: Build APK
        run: bash ./gradlew assembleCovidIndonesiaDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: rdt-open-reader/build/outputs/apk/covidIndonesia/debug/rdt-open-reader-covidIndonesia-debug.apk
  release:
    name: Release APK
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/rdt-open-reader-covidIndonesia-debug.apk
          asset_name: rdt-open-reader-debug.apk
          asset_content_type: application/zip